// Thực đơn cố định (category/dish/promotion) — chuyển từ src/lib/data/_mock.ts (đã xóa,
// không còn nơi nào import trực tiếp sau khi lib/data/*.ts chuyển sang Prisma ở Giai đoạn 9).

// `slug` KHÔNG dịch — nó nằm trong URL (`/thuc-don?category=steak`), đổi là hỏng link cũ.
export const CATEGORIES = [
  { id: "cat-steak", name: "Bít Tết", nameEn: "Steaks", slug: "steak", sortOrder: 1 },
  { id: "cat-khai-vi", name: "Khai Vị", nameEn: "Starters", slug: "khai-vi", sortOrder: 2 },
  { id: "cat-mon-phu", name: "Món Phụ", nameEn: "Sides", slug: "mon-phu", sortOrder: 3 },
  {
    id: "cat-trang-mieng",
    name: "Tráng Miệng",
    nameEn: "Desserts",
    slug: "trang-mieng",
    sortOrder: 4,
  },
  { id: "cat-do-uong", name: "Đồ Uống", nameEn: "Drinks", slug: "do-uong", sortOrder: 5 },
];

export const DISHES = [
  {
    id: "dish-ribeye-uc",
    name: "Bít Tết Ribeye Úc",
    slug: "biet-tet-ribeye-uc",
    description: "Ribeye Úc vân mỡ đều, áp chảo bơ tỏi và lá thyme, ăn kèm sốt tiêu đen.",
    price: 890000,
    imageUrl: "/images/dish-ribeye-uc.jpg",
    categoryId: "cat-steak",
    isAvailable: true,
    isFeatured: true,
    weightGram: 300,
    hasDoneness: true,
  },
  {
    id: "dish-tenderloin-my",
    name: "Bít Tết Thăn Nội Mỹ",
    slug: "biet-tet-than-noi-my",
    description: "Thăn nội bò Mỹ mềm, nướng than hoa, dọn cùng sốt nấm rừng.",
    price: 950000,
    imageUrl: "/images/dish-tenderloin-my.jpg",
    categoryId: "cat-steak",
    isAvailable: true,
    isFeatured: true,
    weightGram: 250,
    hasDoneness: true,
  },
  {
    id: "dish-tbone",
    name: "Bít Tết T-Bone",
    slug: "biet-tet-t-bone",
    description: "T-Bone 2 phần thịt trong 1 miếng, nướng trên bếp than, ăn kèm khoai nướng.",
    price: 1050000,
    imageUrl: "/images/dish-tbone.jpg",
    categoryId: "cat-steak",
    isAvailable: true,
    isFeatured: false,
    weightGram: 400,
    hasDoneness: true,
  },
  {
    id: "dish-suon-nuong",
    name: "Sườn Bò Nướng Sốt BBQ",
    slug: "suon-bo-nuong-sot-bbq",
    description: "Sườn bò ướp 12 giờ, nướng chậm trên than, phết sốt BBQ nhà làm.",
    price: 620000,
    imageUrl: "/images/dish-suon-nuong.jpg",
    categoryId: "cat-steak",
    isAvailable: true,
    isFeatured: true,
    weightGram: 350,
    hasDoneness: false,
  },
  {
    id: "dish-wagyu-a5",
    name: "Bít Tết Wagyu A5",
    slug: "biet-tet-wagyu-a5",
    description: "Wagyu A5 Nhật Bản, áp chảo nhanh giữ độ tan trong miệng, ăn cùng muối Himalaya.",
    price: 1890000,
    imageUrl: "/images/dish-wagyu-a5.jpg",
    categoryId: "cat-steak",
    isAvailable: true,
    isFeatured: true,
    weightGram: 200,
    hasDoneness: true,
  },
  {
    id: "dish-sup-bi-do",
    name: "Súp Bí Đỏ Kem Tươi",
    slug: "sup-bi-do-kem-tuoi",
    description: "Bí đỏ hầm nhuyễn cùng kem tươi, rắc hạt bí rang.",
    price: 95000,
    imageUrl: "/images/dish-sup-bi-do.jpg",
    categoryId: "cat-khai-vi",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-salad-caesar",
    name: "Salad Caesar Tôm Nướng",
    slug: "salad-caesar-tom-nuong",
    description: "Xà lách romaine, phô mai Parmesan, bánh mì nướng giòn và tôm nướng sốt Caesar.",
    price: 145000,
    imageUrl: "/images/dish-salad-caesar.jpg",
    categoryId: "cat-khai-vi",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-escargot",
    name: "Escargot Bơ Tỏi",
    slug: "escargot-bo-toi",
    description: "Ốc sên Pháp áp chảo bơ tỏi và rau mùi tây, dọn nóng trong khay 6 lỗ.",
    price: 185000,
    imageUrl: "/images/dish-escargot.jpg",
    categoryId: "cat-khai-vi",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-khoai-tay-nghien",
    name: "Khoai Tây Nghiền Bơ Tỏi",
    slug: "khoai-tay-nghien-bo-toi",
    description: "Khoai tây nghiền mịn trộn bơ và tỏi phi, dọn kèm hành lá.",
    price: 65000,
    imageUrl: "/images/dish-khoai-tay-nghien.jpg",
    categoryId: "cat-mon-phu",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-mang-tay-nuong",
    name: "Măng Tây Nướng Phô Mai Parmesan",
    slug: "mang-tay-nuong-phomai",
    description: "Măng tây nướng giòn, phủ phô mai Parmesan bào mỏng.",
    price: 85000,
    imageUrl: "/images/dish-mang-tay-nuong.jpg",
    categoryId: "cat-mon-phu",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-nam-portobello",
    name: "Nấm Portobello Nướng",
    slug: "nam-portobello-nuong",
    description: "Nấm Portobello nướng bơ tỏi, dọn cùng sốt truffle nhẹ.",
    price: 75000,
    imageUrl: "/images/dish-nam-portobello.jpg",
    categoryId: "cat-mon-phu",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-creme-brulee",
    name: "Bánh Crème Brûlée",
    slug: "banh-creme-brulee",
    description: "Kem trứng vani nướng, lớp đường caramel giòn phía trên.",
    price: 89000,
    imageUrl: "/images/dish-creme-brulee.jpg",
    categoryId: "cat-trang-mieng",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-tiramisu",
    name: "Tiramisu Ý",
    slug: "tiramisu-y",
    description: "Bánh tiramisu truyền thống, cà phê espresso và phô mai mascarpone.",
    price: 79000,
    imageUrl: "/images/dish-tiramisu.jpg",
    categoryId: "cat-trang-mieng",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-vang-do",
    name: "Rượu Vang Đỏ Cabernet Sauvignon",
    slug: "vang-do-cabernet-sauvignon",
    description: "Vang đỏ Cabernet Sauvignon, phục vụ theo ly 150ml.",
    price: 165000,
    imageUrl: "/images/dish-vang-do.jpg",
    categoryId: "cat-do-uong",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
  {
    id: "dish-mocktail-berry",
    name: "Mocktail Berry Sunset",
    slug: "mocktail-berry-sunset",
    description: "Mocktail dâu tây, việt quất và soda chanh dây, không cồn.",
    price: 75000,
    imageUrl: "/images/dish-mocktail-berry.jpg",
    categoryId: "cat-do-uong",
    isAvailable: true,
    isFeatured: false,
    weightGram: null,
    hasDoneness: false,
  },
];

export const PROMOTIONS = [
  {
    id: "promo-steak-night",
    title: "Đêm Bít Tết Thứ Năm",
    slug: "steak-night",
    description: "Giảm 30% toàn bộ món bít tết mỗi tối thứ Năm.",
    imageUrl: "/images/steak-night.jpg",
    badgeLabel: "PHỔ BIẾN NHẤT",
    badgeOffer: "GIẢM 30%",
    scheduleText: "THỨ 5 HÀNG TUẦN",
    discountType: "PERCENT",
    discountValue: 30,
    scope: "CATEGORY",
    targetCategoryId: "cat-steak",
    targetDishId: null,
    daysOfWeek: "4",
    startTime: null,
    endTime: null,
    minSubtotal: 0,
    startDate: null,
    endDate: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "promo-gio-vang",
    title: "Giờ Vàng Khai Vị",
    slug: "gio-vang-khai-vi",
    description: "Tặng 1 món phụ khi đặt bàn từ 17:00-19:00 các ngày trong tuần.",
    imageUrl: "/images/gio-vang.jpg",
    badgeLabel: "HÀNG NGÀY",
    badgeOffer: "TẶNG MÓN PHỤ",
    scheduleText: "T2-T6, 17:00-19:00",
    discountType: "FIXED",
    discountValue: 75000,
    scope: "ALL",
    targetCategoryId: null,
    targetDishId: null,
    daysOfWeek: "1,2,3,4,5",
    startTime: "17:00",
    endTime: "19:00",
    minSubtotal: 300000,
    startDate: null,
    endDate: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "promo-lang-man",
    title: "Ưu Đãi Lãng Mạn Cho Đôi",
    slug: "uu-dai-lang-man",
    description: "Giảm 200.000đ cho set ăn 2 người vào cuối tuần, sau 18:00.",
    imageUrl: "/images/lang-man.jpg",
    badgeLabel: "LÃNG MẠN",
    badgeOffer: "GIẢM 200K",
    scheduleText: "THỨ 6 - CHỦ NHẬT, SAU 18:00",
    discountType: "FIXED",
    discountValue: 200000,
    scope: "ALL",
    targetCategoryId: null,
    targetDishId: null,
    daysOfWeek: "5,6,0",
    startTime: "18:00",
    endTime: "22:00",
    minSubtotal: 800000,
    startDate: null,
    endDate: null,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "promo-combo-cuoi-tuan",
    title: "Combo Cuối Tuần Gia Đình",
    slug: "combo-cuoi-tuan",
    description: "Giảm 15% cho hóa đơn từ 1.200.000đ vào thứ Bảy và Chủ Nhật.",
    imageUrl: "/images/combo-cuoi-tuan.jpg",
    badgeLabel: "CUỐI TUẦN",
    badgeOffer: "GIẢM 15%",
    scheduleText: "THỨ 7 - CHỦ NHẬT",
    discountType: "PERCENT",
    discountValue: 15,
    scope: "ALL",
    targetCategoryId: null,
    targetDishId: null,
    daysOfWeek: "6,0",
    startTime: null,
    endTime: null,
    minSubtotal: 1200000,
    startDate: null,
    endDate: null,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "promo-dat-nhieu",
    title: "Ưu Đãi Đặt Nhiều",
    slug: "uu-dai-dat-nhieu",
    description: "Giảm 10% cho hóa đơn từ 1.500.000đ, áp dụng mọi ngày.",
    imageUrl: "/images/dat-nhieu.jpg",
    badgeLabel: "TIẾT KIỆM",
    badgeOffer: "GIẢM 10%",
    scheduleText: "MỌI NGÀY",
    discountType: "PERCENT",
    discountValue: 10,
    scope: "ALL",
    targetCategoryId: null,
    targetDishId: null,
    daysOfWeek: "",
    startTime: null,
    endTime: null,
    minSubtotal: 1500000,
    startDate: null,
    endDate: null,
    isActive: true,
    sortOrder: 5,
  },
];
